import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import UsersTable from '@/widgets/usersTable'
import AddUser from '@/widgets/addUser'
import { useState } from 'react'
 
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [opened, setOpened] = useState(false)
 
  return (
    <>
      <Head>
        <title>Штрафов нет</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AddUser opened={opened} setOpened={setOpened} />
        <UsersTable   setOpened={setOpened} />
      </main>
    </>
  );
}
 